version: "2"
services:
  db:
    image: mysql:5.6
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=mangusta3
    ports:
      - 3306:3306
  web:
    image: restfullapi
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=devuser
      - DATABASE_PASSWORD=mangusta3
      - DATABASE_NAME=spring_db
      - DATABASE_PORT=3306
  angular:
    hostname: localhost
    depends_on:
      - web
    container_name: angular-container
    build: ./angular-spring-boot-client
    ports:
      - 80:80